"$schema" = "https://starship.rs/config-schema.json"

format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$python\
$java\
$dotnet\
$golang\
$rust\
$nodejs\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
$kubernetes\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

[os]
disabled = false
style = "bg:#9A348E fg:#FFFFFF"

[username]
show_always = true
style_user = "bg:#9A348E fg:#FFFFFF"
format = "[$user ]($style)"

[directory]
style = "bg:#DA627D fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
style = "bg:#FCA17D fg:#000000"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#FCA17D fg:#000000"
format = "[$all_status$ahead_behind ]($style)"

[python]
style = "bg:#86BBD8 fg:#000000"
format = "[ $symbol($version) ]($style)"

[java]
style = "bg:#86BBD8 fg:#000000"
format = "[ $symbol($version) ]($style)"

[dotnet]
style = "bg:#86BBD8 fg:#000000"
format = "[ $symbol($version) ]($style)"

[golang]
style = "bg:#86BBD8 fg:#000000"
format = "[ $symbol($version) ]($style)"

[rust]
style = "bg:#86BBD8 fg:#000000"
format = "[ $symbol($version) ]($style)"

[nodejs]
style = "bg:#86BBD8 fg:#000000"
format = "[ $symbol($version) ]($style)"

[docker_context]
style = "bg:#06969A fg:#FFFFFF"
format = "[ $symbol$context ]($style)"

[kubernetes]
style = "bg:#06969A fg:#FFFFFF"
format = "[ $symbol$context(:$namespace) ]($style)"
disabled = false

[time]
style = "bg:#33658A fg:#FFFFFF"
format = "[ $time ]($style)"
disabled = false
time_format = "%T"
